### ISSUE TITLE
Error in gulp during build process

### ISSUE THREAD

**Issue by kalinchernev** [ec-europa/ne-theme-framework-dev#3]
Log file: 
[gulp_build_error.txt](https://github.com/ec-europa/ne-theme-framework-dev/files/61040/gulp_build_error.txt)

**Comment by yhuard** [comment]
Unfortunately you're using an outdated version of Node.js which doesn't support natively the `const` keyword (and will reject other ES6 sweets like arrow functions), please update to Node.js >= 4

**Comment by kalinchernev** [comment]
Yes, you're right, I didn't pay attention to that.
These steps solved the issue:
```
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
npm rebuild node-sass
```
The last one was suggested automatically, didn't work without it after the upgrade.
Thanks!
